stages:
 - stage: check
   displayName: Compilation check
   dependsOn: []
   jobs:
     - template: azure/cargo-check.yml@templates
       parameters:
         rust: nightly
 - stage: test
   displayName: Test suite
   dependsOn: check
   jobs:
     - template: azure/test.yml@templates
       parameters:
         rust: nightly
 - stage: style
   displayName: Style linting
   dependsOn: check
   jobs:
     - template: azure/rustfmt.yml@templates
       parameters:
         name: rustfmt
         rust: nightly
         allow_fail: true
     - template: azure/cargo-clippy.yml@templates
       parameters:
         name: clippy
         rust: nightly
         allow_fail: true
 - stage: coverage
   displayName: Code coverage
   dependsOn: test
   jobs:
     - template: azure/coverage.yml@templates
       parameters:
         codecov_token: $(CODECOV_TOKEN_SECRET)
         nightly: true

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: jonhoo
