on:
  pull_request:
    branches:
      - master

name: features

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        features:
          - --no-default-features
          - --features use-rustls
          - --no-default-features --features use-native-tls
          - --all-features
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: stable

      - name: Run check
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings"
        # TODO: solve issue leading to the program not compiling on windows
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          command: clippy
          args: --verbose --all-targets ${{ matrix.features }}

      - name: Run test
        uses: actions-rs/cargo@v1
        # TODO: solve issue causing tests to fail on mac and not compile on windows
        if: ${{ matrix.os != 'macos-latest' && matrix.os != 'windows-latest' }}
        with:
          command: test
          args: --verbose --release ${{ matrix.features }}