on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

name: features

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.features }}
    # runs-on: [self-hosted, linux, X64, rumqtt]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        features:
          - --no-default-features
          - --features use-rustls
          - --no-default-features --features use-native-tls
          - --all-features
        components:
          - rumqttc
          - rumqttd
          - benchmarks
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: stable

      - name: Run check
        uses: actions-rs/cargo@v1
        if: ${{ matrix.os != 'windows-latest' && matrix.components != 'benchmarks' }}
        with:
          command: clippy
          args: --verbose --all-targets ${{ matrix.features }}

      - name: Run rumqttc test
        uses: actions-rs/cargo@v1
        if: ${{ matrix.os != 'macos-latest' }}
        with:
          command: test -p ${{ matrix.components }}
          args: --verbose --release ${{ matrix.features }}