name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup toolchain
      run: rustup override set nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
